
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/neko/.conda/envs/tmp_env/Lib/site-packages/cmake/data/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:5 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/neko/.conda/envs/tmp_env/Lib/site-packages/cmake/data/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:5 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
...
